# Generated by Django 3.1.5 on 2021-01-14 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210110_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='code_postal',
            new_name='zipcode',
        ),
    ]
